name: CI

on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            target: x86_64
          - runner: ubuntu-latest
            target: aarch64
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.platform.target }}
          args: --release --out dist --find-interpreter
          sccache: 'true'
          manylinux: auto
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-linux-${{ matrix.platform.target }}
          path: dist

  windows:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: windows-latest
            target: x64
          - runner: windows-latest
            target: x86
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          architecture: ${{ matrix.platform.target }}
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.platform.target }}
          args: --release --out dist --find-interpreter
          sccache: 'true'
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-windows-${{ matrix.platform.target }}
          path: dist

  macos:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: macos-14
            target: aarch64
          - runner: macos-14
            target: x86_64  # Uncomment this for Intel Macs
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.platform.target }}
          args: --release --out dist --find-interpreter
          sccache: 'true'
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-macos-${{ matrix.platform.target }}
          path: dist

  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch' }}
    needs: [ linux, windows, macos ]
    steps:
      - name: Download Linux x86_64 Wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels-linux-x86_64
          path: dist/linux/x86_64

      - name: Download Linux aarch64 Wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels-linux-aarch64
          path: dist/linux/aarch64

      - name: Download Windows x64 Wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels-windows-x64
          path: dist/windows/x64

      - name: Download Windows x86 Wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels-windows-x86
          path: dist/windows/x86

      - name: Download macOS x86_64 Wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels-macos-x86_64
          path: dist/macos/x86_64

      - name: Download macOS aarch64 Wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels-macos-aarch64
          path: dist/macos/aarch64

      - name: Upload wheels to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/linux/x86_64/*.whl
            dist/linux/aarch64/*.whl
            dist/windows/x64/*.whl
            dist/windows/x86/*.whl
            dist/macos/x86_64/*.whl
            dist/macos/aarch64/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}